version: '1'

services:
  php:
    image: php:5.6-apache
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html:cached
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
